sudo: false

language: node_js

node_js: '8'

cache:
  directories:
    - ~/.npm

install: npm ci --no-save

script:
  - npm run lint:commit
  - npm run lint:md
  - npm run lint
  - npm run test:ci

after_success:
  - npx semantic-release

branches:
  only: master
